Add first capstone project
Abass-rashid/capstone-1 pull request #1
Opened 2022-06-29 12:11 UTC by Abass-rashid

in this PR I have created my first capstone project for a restaurant conference the project is responsive for both desktop and mobile versions

2022-06-29 18:12 UTC, Davidosky007 requested changes
Hi @Abass-rashid 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights ⭐ 
* No linter errors ✔️ 
* Good looking PR ✔️ 
* Well wrriten commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 18:12 UTC, Davidosky007 commented on README.md
> +[Project description video](https://www.loom.com/share/5f3cdb83b7064a709efc47c3f4ab87ce)
* Kindly fix this link as it's broken, am unable to view the video presentation there. below ⬇️  is a screenshot of what i get 
![image](https://user-images.githubusercontent.com/52497246/176502388-14912363-bf41-4274-925d-30052babaf2f.png)

2022-06-29 18:12 UTC, Davidosky007 commented on index.html
> +          <p class="card-text">kimathi street is located opp. corner House Nairobi CBD we are open from 6:00am-10:30pm everyday  </p>
* Kindly work on the margins of this section as the items are not properly arranged as seen in the original design template 
* ## Yours 
![image](https://user-images.githubusercontent.com/52497246/176502852-943747bd-ed7e-4e99-a790-7b391ed4ff39.png)
## Original design 
![image](https://user-images.githubusercontent.com/52497246/176502921-0895e8c5-9122-41b0-b36e-c67f23825d96.png)

2022-06-29 18:12 UTC, Davidosky007 commented on styles.css
> +} */
* Please remove all commented code from your codebase as it makes your codebase bulky and unprofessional

2022-06-30 09:20 UTC, Lordkaito approved these changes
Hi @Abass-rashid, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 10:18 UTC, merged